apiVersion: v1
kind: ConfigMap
metadata:
  name: test-restservice-configmap
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "test-restservice"
data:
  application.properties: |
    spring.application.name=TestRestService
    rest.service.test.value=Pod tests
    management.endpoints.web.exposure.include=refresh
